from .build_enum import from_enumeration


categories = from_enumeration(
    'category',
    'category_name',
    [
        (1, 'AEGOLISM'),
        (2, 'AGILITY'),
        (3, 'ALLIANCE'),
        (4, 'ANIMAL'),
        (5, 'ANTONICA'),
        (6, 'ARMOR CLASS'),
        (7, 'ATTACK'),
        (8, 'BANE'),
        (9, 'BLIND'),
        (10, 'BLOCK'),
        (11, 'CALM'),
        (12, 'CHARISMA'),
        (13, 'CHARM'),
        (14, 'COLD'),
        (15, 'COMBAT ABILITIES'),
        (16, 'COMBAT INNATES'),
        (17, 'CONVERSIONS'),
        (18, 'CREATE ITEM'),
        (19, 'CURE'),
        (20, 'DAMAGE OVER TIME'),
        (21, 'DAMAGE SHIELD'),
        (22, 'DEFENSIVE'),
        (23, 'DESTROY'),
        (24, 'DEXTERITY'),
        (25, 'DIRECT DAMAGE'),
        (26, 'DISARM TRAPS'),
        (27, 'DISCIPLINES'),
        (28, 'DISCORD'),
        (29, 'DISEASE'),
        (30, 'DISEMPOWERING'),
        (31, 'DISPEL'),
        (32, 'DURATION HEALS'),
        (33, 'DURATION TAP'),
        (34, 'ENCHANT METAL'),
        (35, 'ENTHRALL'),
        (36, 'FAYDWER'),
        (37, 'FEAR'),
        (38, 'FIRE'),
        (39, 'FIZZLE RATE'),
        (40, 'FUMBLE'),
        (41, 'HASTE'),
        (42, 'HEALS'),
        (43, 'HEALTH'),
        (44, 'HEALTH MANA'),
        (45, 'HP BUFFS'),
        (46, 'HP TYPE ONE'),
        (47, 'HP TYPE TWO'),
        (48, 'ILLUSION OTHER'),
        (49, 'ILLUSION ADVENTURER'),
        (50, 'IMBUE GEM'),
        (51, 'INVISIBILITY'),
        (52, 'INVULNERABILITY'),
        (53, 'JOLT'),
        (54, 'KUNARK'),
        (55, 'LEVITATE'),
        (56, 'LIFE FLOW'),
        (57, 'LUCLIN'),
        (58, 'MAGIC'),
        (59, 'MANA'),
        (60, 'MANA DRAIN'),
        (61, 'MANA FLOW'),
        (62, 'MELEE GUARD'),
        (63, 'MEMORY BLUR'),
        (64, 'MISC'),
        (65, 'MOVEMENT'),
        (66, 'OBJECTS'),
        (67, 'ODUS'),
        (68, 'OFFENSIVE'),
        (69, 'PET'),
        (70, 'PET HASTE'),
        (71, 'PET MISC BUFFS'),
        (72, 'PHYSICAL'),
        (73, 'PICKLOCK'),
        (74, 'PLANT'),
        (75, 'POISON'),
        (76, 'POWER TAP'),
        (77, 'QUICK HEAL'),
        (78, 'REFLECTION'),
        (79, 'REGEN'),
        (80, 'RESIST BUFF'),
        (81, 'RESIST DEBUFFS'),
        (82, 'RESURRECTION'),
        (83, 'ROOT'),
        (84, 'RUNE'),
        (85, 'SENSE TRAP'),
        (86, 'SHADOWSTEP'),
        (87, 'SHIELDING'),
        (88, 'SLOW'),
        (89, 'SNARE'),
        (90, 'SPECIAL'),
        (91, 'SPELL FOCUS'),
        (92, 'SPELL GUARD'),
        (93, 'SPELLSHIELD'),
        (94, 'STAMINA'),
        (95, 'STATISTIC BUFFS'),
        (96, 'STRENGTH'),
        (97, 'STUN'),
        (98, 'SUM AIR'),
        (99, 'SUM ANIMATION'),
        (100, 'SUM EARTH'),
        (101, 'SUM FAMILIAR'),
        (102, 'SUM FIRE'),
        (103, 'SUM UNDEAD'),
        (104, 'SUM WARDER'),
        (105, 'SUM WATER'),
        (106, 'SUMMON ARMOR'),
        (107, 'SUMMON FOCUS'),
        (108, 'SUMMON FOOD WATER'),
        (109, 'SUMMON UTILITY'),
        (110, 'SUMMON WEAPON'),
        (111, 'SUMMONED'),
        (112, 'SYMBOL'),
        (113, 'TAELOSIA'),
        (114, 'TAPS'),
        (115, 'TECHNIQUES'),
        (116, 'THE PLANES'),
        (117, 'TIMER 1'),
        (118, 'TIMER 2'),
        (119, 'TIMER 3'),
        (120, 'TIMER 4'),
        (121, 'TIMER 5'),
        (122, 'TIMER 6'),
        (123, 'TRANSPORT'),
        (124, 'UNDEAD'),
        (125, 'UTILITY BENEFICIAL'),
        (126, 'UTILITY DETRIMENTAL'),
        (127, 'VELIOUS'),
        (128, 'VISAGES'),
        (129, 'VISION'),
        (130, 'WISDOM INTELLIGENCE'),
        (131, 'TRAPS'),
        (132, 'AURAS'),
        (133, 'ENDURANCE'),
        (134, 'SERPENTS SPINE'),
        (135, 'CORRUPTION'),
        (136, 'LEARNING'),
        (137, 'CHROMATIC'),
        (138, 'PRISMATIC'),
        (139, 'SUM SWARM'),
        (140, 'DELAYED'),
        (141, 'TEMPORARY'),
        (142, 'TWINCAST'),
        (143, 'SUM BODYGUARD'),
        (144, 'HUMANOID'),
        (145, 'HASTE SPELL FOCUS'),
        (146, 'TIMER 7'),
        (147, 'TIMER 8'),
        (148, 'TIMER 9'),
        (149, 'TIMER 10'),
        (150, 'TIMER 11'),
        (151, 'TIMER 12'),
        (152, 'HATRED'),
        (153, 'FAST'),
        (154, 'ILLUSION SPECIAL'),
        (155, 'TIMER 13'),
        (156, 'TIMER 14'),
        (157, 'TIMER 15'),
        (158, 'TIMER 16'),
        (159, 'TIMER 17'),
        (160, 'TIMER 18'),
        (161, 'TIMER 19'),
        (162, 'TIMER 20'),
        (163, 'ALARIS'),
        (164, 'COMBINATION'),
        (165, 'INDEPENDENT'),
        (166, 'SKILL ATTACKS'),
        (167, 'INCOMING'),
        (168, 'CURSE'),
        (169, 'TIMER 21'),
        (170, 'TIMER 22'),
        (171, 'TIMER 23'),
        (172, 'TIMER 24'),
        (173, 'TIMER 25'),
        (174, 'DRUNKENNESS'),
        (175, 'THROWING'),
        (176, 'MELEE DAMAGE'),
    ]
)
