from .build_enum import from_enumeration


target_types = from_enumeration(
    'target_type',
    'target_type_name',
    [
        (0, 'None'),
        (1, 'Line Of Sight'),
        (2, 'AEPC v1'),
        (3, 'Group v1'),
        (4, 'PBAE'),
        (5, 'Single'),
        (6, 'Self'),
        (8, 'Target Area'),
        (9, 'Target Animal'),
        (10, 'Target Undead'),
        (11, 'Target Summoned'),
        (13, 'Target Drain'),
        (14, 'Pet'),
        (15, 'Target Corpse'),
        (16, 'Target Plant'),
        (17, 'Target Giants'),
        (18, 'Target Dragons'),
        (19, 'Target Coldain'),
        (20, 'Target AE Drain'),
        (24, 'Target AE Undead'),
        (25, 'Target AE Summoned'),
        (32, 'Hate List'),
        (33, 'Hate List All'),
        (34, 'Target Cursed'),
        (35, 'Target Muramite'),
        (36, 'Caster AreaPC'),
        (37, 'Caster AreaNPC'),
        (38, 'Pet v2'),
        (39, 'Target PC'),
        (40, 'AEPC v2'),
        (41, 'Group v2'),
        (42, 'Directional Cone'),
        (43, 'Single Grouped'),
        (44, 'Beam'),
        (45, 'Free Target'),
        (46, 'Target Of Target'),
        (47, 'Pet Owner'),
        (50, 'Area Detrimental'),
        (52, 'Target Beneficial'),
    ]
)
